ibexa/content-forms

- src/bundle/Resources/views/content_name/content_name.html.twig
https://issues.ibexa.co/browse/IBX-1543
> IBX-1543: Replaced ez_content_name function

- features/User/Registration/user_registration.feature
- src/bundle/Resources/views/Content/content_edit.html.twig
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1689](https://issues.ibexa.co/browse/IBX-1689)
| **Type**                                   | improvement
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes
Changed all eZ/ez- frontend classes/variables to ibexa
Related PRs:
- https://github.com/ibexa/admin-ui/pull/111
- https://github.com/ibexa/calendar/pull/15
- https://github.com/ibexa/commerce-admin-ui/pull/23
- https://github.com/ibexa/commerce-base-design/pull/11
- https://github.com/ibexa/commerce-checkout/pull/10
- https://github.com/ibexa/commerce-fieldtypes/pull/11
- https://github.com/ibexa/commerce-page-builder/pull/11
- …
> IBX-1689: Change all ez- classes/IDs and eZ variables in frontend part

- src/bundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPass.php
- src/bundle/Resources/config/feature_contexts.yaml
- src/bundle/Resources/config/fieldtypes.yaml
- src/bundle/Resources/config/routing.yaml
- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/views.yaml
- src/lib/Content/View/Builder/ContentCreateViewBuilder.php
- src/lib/Content/View/Builder/ContentEditViewBuilder.php
- src/lib/Content/View/ContentCreateSuccessView.php
- src/lib/Content/View/ContentEditSuccessView.php
- src/lib/Content/View/Filter/ContentCreateViewFilter.php
- src/lib/Content/View/Filter/ContentEditViewFilter.php
- src/lib/Validator/Constraints/FieldValue.php
- tests/lib/Validator/Constraints/FieldValueTest.php
> IBX-1853: Rebranded services names

- src/bundle/Controller/ContentEditController.php
- src/bundle/Resources/config/routing.yaml
- src/lib/Behat/Context/UserRegistrationContext.php
- src/lib/Form/Processor/ContentFormProcessor.php
- src/lib/Form/Processor/User/UserCancelFormProcessor.php
- src/lib/Form/Processor/User/UserCreateFormProcessor.php
- src/lib/Form/Processor/User/UserUpdateFormProcessor.php
- src/lib/Form/Type/FieldType/DateFieldType.php
> IBX-1998: Rebranded routes in ibexa/content-forms repository

- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/views.yaml
> IBX-1696: Removed class parameters from ibexa/content-forms repository

- src/bundle/Controller/UserRegisterController.php
- src/contracts/Data/Content/FieldData.php
- src/lib/Data/Content/ContentCreateData.php
- src/lib/Data/Content/ContentUpdateData.php
- src/lib/Data/ContentTranslationData.php
- src/lib/Data/User/UserUpdateData.php
- src/lib/Form/Processor/ContentFormProcessor.php
- src/lib/Form/Type/Content/ContentEditType.php
- src/lib/Form/Type/User/BaseUserType.php
- src/lib/Form/Type/User/UserCreateType.php
- src/lib/Form/Type/User/UserUpdateType.php
- src/lib/User/View/UserRegisterConfirmView.php
- src/lib/User/View/UserRegisterFormView.php
> IBX-1853: Used rebranded namespaces in comments

- src/lib/Data/Mapper/ContentCreateMapper.php
> IBX-1853: Used rebranded namespaces in code

- composer.json
JIRA: https://issues.ibexa.co/browse/IBX-2322
> [Behat] Rebranding

- src/lib/Data/User/UserCreateData.php
- src/lib/Form/Type/FieldType/UserAccountFieldType.php
| Question      | Answer
| ------------- | ---
| Tickets       |  [IBX-2493](https://issues.ibexa.co/browse/IBX-2493) 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| License       | [GPL-2.0](https://github.com/ibexa/admin-ui/blob/main/LICENSE)
https://github.com/ibexa/user/pull/35
> IBX-2493: Added invitation intent with role assigment handling for user creation

- src/lib/Validator/Constraints/FieldValueValidator.php
JIRA: https://issues.ibexa.co/browse/IBX-3289
> IBX-3289: Fixed validation exception on nulled but required fields

- src/bundle/Resources/translations/validators.en.xliff
- src/lib/Form/Type/FieldType/UserAccountFieldType.php
https://issues.ibexa.co/browse/IBX-3409
> IBX-3409: Added validation message

- src/lib/Behat/Context/UserRegistrationContext.php
Please see for the context of this changes: https://github.com/ibexa/content-forms/pull/43
> Corrected Behat test

- src/lib/Data/Mapper/UserUpdateMapper.php
| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-6645
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ibexa/admin-ui/blob/main/LICENSE)
> IBX-7333: User profile

- src/lib/Form/Processor/ContentFormProcessor.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-7020](https://issues.ibexa.co/browse/IBX-7020)
| **Type**                                   | bug
| **Target Ibexa version** | `v4.6` 
| **BC breaks**                          | no
| **Doc needed**                       | no
Seems like a typo.
Related PR: https://github.com/ibexa/admin-ui/pull/1030
> IBX-7020: Fixed redirect after saving and closing

- features/ContentEdit/create_without_draft.feature
- features/FieldTypeForm/checkbox_fieldtype_edit_form.feature
- features/FieldTypeForm/selection_fieldtype_edit_form.feature
- features/FieldTypeForm/textline_fieldtype_edit_form.feature
- features/FieldTypeForm/user_fieldtype_edit_form.feature
- src/lib/Behat/Context/ContentEditContext.php
- src/lib/Behat/Context/ContentTypeContext.php
- src/lib/Behat/Context/FieldTypeFormContext.php
- src/lib/Behat/Context/UserRegistrationContext.php
- src/lib/Content/View/Builder/ContentCreateViewBuilder.php
| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-7409](https://issues.ibexa.co/browse/IBX-7409)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
Changed Content Type to Content type
> IBX-7409: Changed Content Type to content type

- src/lib/Form/EventSubscriber/SuppressValidationSubscriber.php
| Question             | Answer                                                |
|----------------------|-------------------------------------------------------|
| **JIRA issue**       | [IBX-7957](https://issues.ibexa.co/browse/IBX-7957)   |
| **Type**             | bug                                                   |
| **Target version**   | `v4.6`                                                |
| **BC breaks**        | no                                                    |
| **Doc needed**       | no                                                    |
As title suggest.
> IBX-7957: Suppressed validation on `Save and Close`

- composer.json
- phpunit.xml.dist
- src/contracts/Content/Form/Provider/GroupedContentFormFieldsProviderInterface.php
- tests/lib/Content/Form/Provider/GroupedContentFormFieldsProviderTest.php
- tests/lib/FieldType/DataTransformer/FieldValueTransformerTest.php
- tests/lib/FieldType/DataTransformer/RelationListValueTransformerTest.php
- tests/lib/FieldType/FieldTypeFormMapperDispatcherTest.php
- tests/lib/FieldType/Mapper/BaseMapperTest.php
- tests/lib/FieldType/Mapper/FormTypeBasedFieldValueFormMapperTest.php
- tests/lib/FieldType/Mapper/UserAccountFieldValueFormMapperTest.php
- tests/lib/Validator/Constraints/PasswordTest.php
- tests/lib/Validator/Constraints/PasswordValidatorTest.php
- tests/lib/Validator/Constraints/UserAccountPasswordTest.php
- tests/lib/Validator/Constraints/UserAccountPasswordValidatorTest.php
| :ticket: Issue | IBX-8121 |
This PR fixes code style issues for Ibexa DXP 5.0.
> IBX-8121: Fixed code style for 5.0

- src/lib/Behat/Context/PagelayoutContext.php
- src/lib/EventListener/ViewTemplatesListener.php
| :ticket: Issue | IBX-8534 |
- https://github.com/ibexa/core/pull/435
> IBX-8534: Renamed pagelayout parameter

- src/lib/ConfigResolver/MaxUploadSize.php
- src/lib/FieldType/Mapper/SelectionFormMapper.php
| :ticket: Issue | IBX-XXXXX |
Followup including code review suggestions from https://github.com/ibexa/content-forms/pull/95.
> Typehints and PHP8.3 code adaptation followup

- src/lib/Content/View/Builder/ContentEditViewBuilder.php
| :ticket: Issue | IBX-10420 |
> IBX-10420: Reloaded content as it is out of date after going through action dispatcher

- src/lib/Content/View/Builder/ContentEditViewBuilder.php
- src/lib/Validator/ValidationErrorsProcessor.php
| :ticket: Issue | IBX-10507 |
Allowed nullable type declarations for method parameters across the codebase
> IBX-10507: Allowed nullable type declarations for method parameters across the codebase

- .github/workflows/browser-tests.yaml
- .github/workflows/ci.yaml
- phpstan-baseline.neon
> [CI] Aligned secrets + regenerated PHPStan baseline
